# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20180731_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='color_availability',
        ),
        migrations.RemoveField(
            model_name='design',
            name='design_colors',
        ),
        migrations.RemoveField(
            model_name='design',
            name='sex',
        ),
    ]
