# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-02 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20180801_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='design',
        ),
        migrations.RemoveField(
            model_name='design',
            name='image',
        ),
        migrations.AddField(
            model_name='design',
            name='design_file',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='display_image',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='licenses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='products_ordered', to='market.Design'),
        ),
        migrations.DeleteModel(
            name='Spec',
        ),
    ]
