# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-06 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_design_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
