# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-09 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20180809_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
