# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-13 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_design_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
