# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-16 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20180813_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='charge_id',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
