# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-07 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_order_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='token_id',
            field=models.IntegerField(default=0),
        ),
    ]
